import Head from "next/head";
import Image from "next/image";
import {
  Navbar,
  StickyBar,
  Notification,
  Video,
  Movies,
  RunningMovies,
} from "../components";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Apple TV+ -Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          // crossorigin="anonymous"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <StickyBar />
        <Notification />
        <Video />
        <Movies />
        <RunningMovies />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
