import Head from "next/head";
import Image from "next/image";
import { Navbar, StickyBar, Notification, Video } from "../components";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Apple TV+ -Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <StickyBar />
        <Notification />
        <Video />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
